<a href="https://colab.research.google.com/github/Bart061/data-science/blob/main/3KURS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__


'1.18.5'

In [9]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [10]:
np.linalg.norm(v1)

4.123105625617661

In [12]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [16]:
## odleglosc 2 pkt na plaszczyznie
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p - q)

5.0

In [17]:
## przestren R3


In [19]:
p = np.array([3,0,1])
q = np.array([0,4,2])

np.linalg.norm(p-q)

5.0990195135927845

In [20]:
### mnozenie macierzy

In [24]:
A = np.array([[2,4], [-1,3]])

In [26]:
round(np.linalg.det(A))

10.0

In [27]:
## Slad macierzy to suma elementow na przekatnej

In [28]:
np.trace(A)

5

In [29]:
A = np.array([[2,4],[1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [30]:
B = np.array([[10],[-1]])

In [34]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])