<a href="https://colab.research.google.com/github/Bart061/data-science/blob/main/kurs2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
np.zeros(shape=(4,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [14]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [16]:
np.arange(start=0, stop=1, step=0.25)

array([0.  , 0.25, 0.5 , 0.75])

In [17]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
A.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [26]:
A+B


array([6, 0, 7, 4])

In [27]:
A-B

array([0, 2, 1, 0])

In [28]:
A*B


array([ 9, -1, 12,  4])

In [29]:
A/B


array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [30]:
A + 3

array([6, 4, 7, 5])

In [31]:
2 *A


array([6, 2, 8, 4])

In [32]:
np.add(A,B)

array([6, 0, 7, 4])

In [34]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [35]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [36]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [40]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [41]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [44]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [45]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [46]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [47]:
######################################################################## LICZBY PSEUDOLOSOWE


In [49]:
np.random.seed(0)

In [50]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [51]:
np.random.rand(10,4)

array([[0.79172504, 0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835, 0.36371077]])

In [52]:
np.random.rand()

0.5701967704178796

In [54]:
np.random.rand(10,2)

array([[0.11037514, 0.65632959],
       [0.13818295, 0.19658236],
       [0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318]])

In [59]:
np.random.randint(10)

2

In [61]:
np.random.randint(low=10, high=101, size=10)

array([30, 91, 60, 37, 24, 51, 68, 75, 46, 20])

In [64]:
np.random.choice(['python','java','sql'])

'python'

In [65]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.random.shuffle(data)

In [67]:
data

array([5, 1, 4, 9, 8, 6, 7, 0, 3, 2])

In [69]:
###################################### PODSTAWOWE FUNKCJE


In [71]:
np.exp(1)

2.718281828459045

In [72]:
np.sqrt(9)

3.0

In [74]:
np.all([2,3,1])

True

In [78]:
np.any([0,0,0])

False

In [79]:
bool(1.3)

True

In [82]:
A = np.random.rand(5)
A


array([0.29743695, 0.81379782, 0.39650574, 0.8811032 , 0.58127287])

In [84]:
np.argmax(A)

3

In [85]:
A[np.argmax(A)]

0.8811031971111616

In [86]:
A[np.argmin(A)]

0.29743695085513366

In [87]:
np.argsort(A)

array([0, 2, 4, 1, 3])

In [89]:
np.max(A)

0.8811031971111616

In [90]:
np.mean(A)

0.5940233162303231

In [91]:
np.median(A)

0.5812728726358587

In [92]:
np.std(A)

0.2270924608641256

In [93]:
############################################################## Indeksowanie

In [96]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [99]:
A[8:]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [100]:
A[:4]

array([0, 1, 2, 3])

In [101]:
A[-1]

19

In [103]:
A[10:15]

array([10, 11, 12, 13, 14])

In [106]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [107]:
A[0]

array([0, 1, 2, 3, 4])

In [109]:
A[:,2]

array([ 2,  7, 12, 17])

In [110]:
A[:,-1]

array([ 4,  9, 14, 19])

In [111]:
A[1,2]

7

In [117]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [118]:
####################### intracje oi tab

In [120]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [121]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [122]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [123]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [124]:
A.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6, 14],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [125]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [126]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [130]:
################### MASKI LOGICZNE
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [132]:
A = A.reshape (10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [133]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [134]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [136]:
B =np.bitwise_and(A > -5, A <5)

In [137]:
A [B]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [138]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])